### ISSUE TITLE
the code of   exchange information between the two branches  in aia_net.py seems not math to the  diagram?

### ISSUE THREAD

**Issue by l2009312042** [yuguochencuc/DB-AIAT#2]
from line 188 to 190 ,      
` if i >=1:
            output_mag_i = input_mag + output_list_ri[-1]
 else: output_mag_i = input_mag`

from the diagram,i think it should be   output_mag_i = output_list_mag[-1]+ output_list_ri[-1],is that right?

**Comment by yuguochencuc** [comment]
Sorry for my negligence. I upload the original wrong version of aia_net.py. You are right. It should be output_mag_i = output_list_mag[-1]+ output_list_ri[-1]. I will correct it right now. Thanks.

**Comment by l2009312042** [comment]
that 's good  thanks for your relp.
